import { Rules } from "./Rules";
import { RuleValidator } from "./rules/Rule";
import { Messages, MessagesStatic, ValidationMessages } from "./Messages";
import { Errors } from "./Errors";
export declare type AttributeFormatter = (attribute: string) => string;
export declare type AsyncCallback = (result: boolean) => void;
export declare class Validator {
    static Promise: PromiseConstructor;
    static lang: string;
    static attributeFormatter: AttributeFormatter;
    static Messages: MessagesStatic;
    input: any;
    rules: Rules;
    messages: Messages;
    errors: Errors;
    constructor(input: any, rules: any, messages?: any);
    check(): boolean;
    checkAsync(passes?: AsyncCallback, fails?: AsyncCallback): Promise<boolean>;
    passes(callback?: AsyncCallback): boolean | Promise<boolean>;
    fails(callback?: AsyncCallback): boolean | Promise<boolean>;
    setAttributeNames(attributeNames: any): void;
    static make(input: any, rules: any, messages?: any): Validator;
    static setMessages(lang: string, messages: ValidationMessages): void;
    static getMessages(lang?: string): ValidationMessages;
    static useLang(lang: string): void;
    static getDefaultLang(): string;
    static setAttributeFormatter(formatter: AttributeFormatter): void;
    static register(name: string, fn: RuleValidator, message?: string): void;
    static registerAsync(name: string, fn: RuleValidator, message?: string): void;
}
